# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d72b1a13cde4c3790b8280451cc2b2c56863db431f5672fefc6f237b844689c6d992c499a9022cd0cb2f2b151b6784d7246a03a72a43faf03a7964b1b9d319e

test:
  secret_key_base: 0644f3f9b61e229418b0cae20e9e424c3d9dfecc1e858eab59bc7244b3dfd73097a512e4da569dc43a5ba45ff87050f8f973546695fa752834f6d9beffc04124

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
